# Configuration file for snakemake pipeline

# Dataset samples
samples: "config/samples.csv"
out_dir: "AA/Roar"

# Parameters
# define method specific parameters here

# Settings
envs: "envs"
gtf: "mm_multiple.gtf"
scripts: "workflow/scripts"
local_log: "logs/local_log"
cluster_log: "logs/cluster_log"
